version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    rust: "latest"
  jobs:
    install:
      - pip install uv
      - uv sync --group docs
    build:
      html:
        - uv run mkdocs build -d $READTHEDOCS_OUTPUT/html
